---
  name: "ONLY TEST"
  on:
    workflow_dispatch: {}
    push:
      branches:
        - "main"
      paths-ignore:
        - "**/*.md"
  concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: false
  jobs:
    install-dependencies:
      name: "install dependencies"
      runs-on: "ubuntu-latest"
      steps:
        -
          name: "Checkout under $GITHUB_WORKSPACE"
          uses: "actions/checkout@master"
          with:
            ref: "main"
        -
          name: "Set up NodeJS"
          uses: "actions/setup-node@master"
          with:
            node-version: "16.20.0"
        -
          name: "Install dependencies"
          run: "npm install"
        -
          name: "Cache"
          uses: "actions/cache@main"
          with:
            path: "./*"
            key: "${{ github.sha }}-cache"
    test:
      name: "test"
      runs-on: "ubuntu-latest"
      needs: "install-dependencies"
      steps:
        -
          name: "Set up NodeJS"
          uses: "actions/setup-node@master"
          with:
            node-version: "16.20.0"
        -
          name: "Cache"
          uses: "actions/cache@main"
          with:
            path: "./*"
            key: "${{ github.sha }}-cache"
        -
          name: "Build core package"
          run: "npm run core:build"
        -
          name: "Run tests"
          run: "npm run cli:test-coverage"